/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ContractTypeNameRead extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "en" })
    en?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "fr" })
    fr?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "nl" })
    nl?: string;
}
