/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ContractTypeNameRead } from "./contracttypenameread";
import { Expose, Type } from "class-transformer";

export class ContractTypeRead extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    @Type(() => ContractTypeNameRead)
    name?: ContractTypeNameRead;
}
