/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ContractAutomaticRenewal extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "number_of_renewals" })
    numberOfRenewals?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "renewal_period" })
    renewalPeriod?: string;
}
