/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum ContractPhase {
    Tender = "tender",
    Ongoing = "ongoing",
    InTermination = "in_termination",
    Ended = "ended",
    InReview = "in_review",
}
