/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ContractTypeRead } from "./contracttyperead";
import { Expose, Type } from "class-transformer";

export class ContractTypeCollection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ContractTypeRead })
    @Expose({ name: "data" })
    @Type(() => ContractTypeRead)
    data?: ContractTypeRead[];
}
