/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../../sdk/types";
import { ContractPhase } from "./contractphase";
import { ContractRenewal } from "./contractrenewal";
import { ContractTermination } from "./contracttermination";
import { CustomFieldValueWrite } from "./customfieldvaluewrite";
import { Expose, Transform, Type } from "class-transformer";

export class ContractWrite extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "contract_types" })
    contractTypes?: number[];

    @SpeakeasyMetadata({ elemType: CustomFieldValueWrite })
    @Expose({ name: "custom_field_values" })
    @Type(() => CustomFieldValueWrite)
    customFieldValues?: CustomFieldValueWrite[];

    @SpeakeasyMetadata()
    @Expose({ name: "departments" })
    departments?: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "documents" })
    documents?: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "dossier_id" })
    dossierId: number;

    @SpeakeasyMetadata()
    @Expose({ name: "duration" })
    duration?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "end_date" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    endDate?: RFCDate;

    @SpeakeasyMetadata()
    @Expose({ name: "is_open_ended" })
    isOpenEnded?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "legal_entities" })
    legalEntities?: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "offices" })
    offices?: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "owner_id" })
    ownerId?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "phase" })
    phase?: ContractPhase;

    @SpeakeasyMetadata()
    @Expose({ name: "relations" })
    relations?: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "renewal" })
    @Type(() => ContractRenewal)
    renewal?: ContractRenewal;

    @SpeakeasyMetadata()
    @Expose({ name: "start_date" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    startDate?: RFCDate;

    @SpeakeasyMetadata()
    @Expose({ name: "termination" })
    @Type(() => ContractTermination)
    termination?: ContractTermination;
}
