/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ContractRead } from "./contractread";
import { Pagination } from "./pagination";
import { Expose, Type } from "class-transformer";

export class ContractCollection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ContractRead })
    @Expose({ name: "data" })
    @Type(() => ContractRead)
    data?: ContractRead[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => Pagination)
    meta?: Pagination;
}
