/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CustomFieldRead } from "./customfieldread";
import { Pagination } from "./pagination";
import { Expose, Type } from "class-transformer";

export class CustomFieldCollection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: CustomFieldRead })
    @Expose({ name: "data" })
    @Type(() => CustomFieldRead)
    data?: CustomFieldRead[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => Pagination)
    meta?: Pagination;
}
