/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DocumentRead } from "./documentread";
import { Pagination } from "./pagination";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class DocumentCollection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: DocumentRead })
    @Expose({ name: "data" })
    @Type(() => DocumentRead)
    data?: DocumentRead[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => Pagination)
    meta?: Pagination;
}
