/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ContractRead } from "./contractread";
import { CustomFieldValueRead } from "./customfieldvalueread";
import { DocumentVersionRead } from "./documentversionread";
import { DossierRead } from "./dossierread";
import { Expose, Transform, Type } from "class-transformer";

export class DocumentRead extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ContractRead })
    @Expose({ name: "contracts" })
    @Type(() => ContractRead)
    contracts?: ContractRead[];

    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt?: Date;

    @SpeakeasyMetadata({ elemType: CustomFieldValueRead })
    @Expose({ name: "custom_field_values" })
    @Type(() => CustomFieldValueRead)
    customFieldValues?: CustomFieldValueRead[];

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata({ elemType: DossierRead })
    @Expose({ name: "dossiers" })
    @Type(() => DossierRead)
    dossiers?: DossierRead[];

    @SpeakeasyMetadata()
    @Expose({ name: "download_url" })
    downloadUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "owner_id" })
    ownerId?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "permalink" })
    permalink?: string;

    @SpeakeasyMetadata({ elemType: DocumentVersionRead })
    @Expose({ name: "versions" })
    @Type(() => DocumentVersionRead)
    versions?: DocumentVersionRead[];
}
