/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class DocumentVersionRead extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "detected_lanugage" })
    detectedLanugage?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "download_url" })
    downloadUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "file_size" })
    fileSize?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "file_type" })
    fileType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "mime_type" })
    mimeType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}
