/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LegalEntityRead } from "./legalentityread";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class LegalEntityCollection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: LegalEntityRead })
    @Expose({ name: "data" })
    @Type(() => LegalEntityRead)
    data?: LegalEntityRead[];
}
