/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Pagination } from "./pagination";
import { UserRead } from "./userread";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class UserCollection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: UserRead })
    @Expose({ name: "data" })
    @Type(() => UserRead)
    data?: UserRead[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => Pagination)
    meta?: Pagination;
}
