/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class CreateOfficeRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    officeWrite?: shared.OfficeWrite;

    /**
     * Id of the company
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=company" })
    company: number;
}

export class CreateOffice422ApplicationJSONErrors extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "errors" })
    errors?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "field" })
    field?: string;
}

/**
 * Invalid data posted
 */
export class CreateOffice422ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: CreateOffice422ApplicationJSONErrors })
    @Expose({ name: "errors" })
    @Type(() => CreateOffice422ApplicationJSONErrors)
    errors?: CreateOffice422ApplicationJSONErrors[];

    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Forbidden
 */
export class CreateOffice403ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Unauthenticated
 */
export class CreateOffice401ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Created
 */
export class CreateOffice201ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.OfficeRead)
    data?: shared.OfficeRead;
}

export class CreateOfficeResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Created
     */
    @SpeakeasyMetadata()
    createOffice201ApplicationJSONObject?: CreateOffice201ApplicationJSON;

    /**
     * Unauthenticated
     */
    @SpeakeasyMetadata()
    createOffice401ApplicationJSONObject?: CreateOffice401ApplicationJSON;

    /**
     * Forbidden
     */
    @SpeakeasyMetadata()
    createOffice403ApplicationJSONObject?: CreateOffice403ApplicationJSON;

    /**
     * Invalid data posted
     */
    @SpeakeasyMetadata()
    createOffice422ApplicationJSONObject?: CreateOffice422ApplicationJSON;
}
