/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class CreateDepartmentSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    oAuth2: string;

    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    personalAccessToken: string;
}

export class CreateDepartmentRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    departmentWrite?: shared.DepartmentWrite;

    /**
     * Id of the company
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=company" })
    company: number;
}

export class CreateDepartment422ApplicationJSONErrors extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "errors" })
    errors?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "field" })
    field?: string;
}

/**
 * Invalid data posted
 */
export class CreateDepartment422ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: CreateDepartment422ApplicationJSONErrors })
    @Expose({ name: "errors" })
    @Type(() => CreateDepartment422ApplicationJSONErrors)
    errors?: CreateDepartment422ApplicationJSONErrors[];

    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Forbidden
 */
export class CreateDepartment403ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Unauthenticated
 */
export class CreateDepartment401ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Created
 */
export class CreateDepartment201ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.DepartmentRead)
    data?: shared.DepartmentRead;
}

export class CreateDepartmentResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Created
     */
    @SpeakeasyMetadata()
    createDepartment201ApplicationJSONObject?: CreateDepartment201ApplicationJSON;

    /**
     * Unauthenticated
     */
    @SpeakeasyMetadata()
    createDepartment401ApplicationJSONObject?: CreateDepartment401ApplicationJSON;

    /**
     * Forbidden
     */
    @SpeakeasyMetadata()
    createDepartment403ApplicationJSONObject?: CreateDepartment403ApplicationJSON;

    /**
     * Invalid data posted
     */
    @SpeakeasyMetadata()
    createDepartment422ApplicationJSONObject?: CreateDepartment422ApplicationJSON;
}
