/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export * from "./createcontract";
export * from "./createdepartment";
export * from "./createoffice";
export * from "./createrelation";
export * from "./createtask";
export * from "./currentuser";
export * from "./deletecontract";
export * from "./deletedepartment";
export * from "./deletedocument";
export * from "./deleteoffice";
export * from "./deleterelation";
export * from "./deletetask";
export * from "./getcontract";
export * from "./getdepartment";
export * from "./getdocument";
export * from "./getoffice";
export * from "./getrelation";
export * from "./gettask";
export * from "./listcontracts";
export * from "./listcontracttypes";
export * from "./listcustomfields";
export * from "./listdepartments";
export * from "./listdocuments";
export * from "./listlegalentities";
export * from "./listoffices";
export * from "./listrelations";
export * from "./listsubfolders";
export * from "./listtasks";
export * from "./listusers";
export * from "./updatecontract";
export * from "./updatedepartment";
export * from "./updatedocument";
export * from "./updateoffice";
export * from "./updaterelation";
export * from "./updatetask";
