/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

/**
 * Return documents currently having this status in the eSigning process, can be comma separated
 */
export enum EsigningStatus {
    NotSent = "not_sent",
    SentToLegal = "sent_to_legal",
    LegalDeclined = "legal_declined",
    Sent = "sent",
    Signed = "signed",
    RejectedBySigner = "rejected_by_signer",
    FinishedButPartiallySigned = "finished_but_partially_signed",
    Revoked = "revoked",
}

export class ListDocumentsRequest extends SpeakeasyBase {
    /**
     * Id of the company
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=company" })
    company: number;

    /**
     * Return documents currently having this status in the eSigning process, can be comma separated
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=esigning_status" })
    esigningStatus?: EsigningStatus;

    /**
     * Return documents where e-signing was updated after the given date
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=esigning_updated_after" })
    esigningUpdatedAfter?: Date;

    /**
     * The page to retrieve
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=page" })
    page?: number;

    /**
     * Return documents linked to a relation
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=relation_id" })
    relationId?: number;

    /**
     * Return documents e-signed after the given date
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=signed_after" })
    signedAfter?: Date;
}

/**
 * Forbidden
 */
export class ListDocumentsDocumentsResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Unauthenticated
 */
export class ListDocumentsResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

export class ListDocumentsResponse extends SpeakeasyBase {
    /**
     * Unauthenticated
     */
    @SpeakeasyMetadata()
    fourHundredAndOneApplicationJsonObject?: ListDocumentsResponseBody;

    /**
     * Forbidden
     */
    @SpeakeasyMetadata()
    fourHundredAndThreeApplicationJsonObject?: ListDocumentsDocumentsResponseBody;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    documentCollection?: shared.DocumentCollection;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
