/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class UpdateRelationRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    relationWrite?: shared.RelationWrite;

    /**
     * Id of the company
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=company" })
    company: number;

    /**
     * Id of the relation
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=relation" })
    relation: number;
}

export class UpdateRelation422ApplicationJSONErrors extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "errors" })
    errors?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "field" })
    field?: string;
}

/**
 * Invalid data posted
 */
export class UpdateRelation422ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: UpdateRelation422ApplicationJSONErrors })
    @Expose({ name: "errors" })
    @Type(() => UpdateRelation422ApplicationJSONErrors)
    errors?: UpdateRelation422ApplicationJSONErrors[];

    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Not Found
 */
export class UpdateRelation404ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Forbidden
 */
export class UpdateRelation403ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Unauthenticated
 */
export class UpdateRelation401ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * OK
 */
export class UpdateRelation200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.RelationRead)
    data?: shared.RelationRead;
}

export class UpdateRelationResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    updateRelation200ApplicationJSONObject?: UpdateRelation200ApplicationJSON;

    /**
     * Unauthenticated
     */
    @SpeakeasyMetadata()
    updateRelation401ApplicationJSONObject?: UpdateRelation401ApplicationJSON;

    /**
     * Forbidden
     */
    @SpeakeasyMetadata()
    updateRelation403ApplicationJSONObject?: UpdateRelation403ApplicationJSON;

    /**
     * Not Found
     */
    @SpeakeasyMetadata()
    updateRelation404ApplicationJSONObject?: UpdateRelation404ApplicationJSON;

    /**
     * Invalid data posted
     */
    @SpeakeasyMetadata()
    updateRelation422ApplicationJSONObject?: UpdateRelation422ApplicationJSON;
}
