/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class UpdateDocumentSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    oAuth2: string;

    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    personalAccessToken: string;
}

export class UpdateDocumentRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    documentWrite?: shared.DocumentWrite;

    /**
     * Id of the company
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=company" })
    company: number;

    /**
     * Id of the document
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=document" })
    document: number;
}

/**
 * Not Found
 */
export class UpdateDocument404ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Forbidden
 */
export class UpdateDocument403ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Unauthenticated
 */
export class UpdateDocument401ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * OK
 */
export class UpdateDocument200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.DocumentRead)
    data?: shared.DocumentRead;
}

export class UpdateDocumentResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    updateDocument200ApplicationJSONObject?: UpdateDocument200ApplicationJSON;

    /**
     * Unauthenticated
     */
    @SpeakeasyMetadata()
    updateDocument401ApplicationJSONObject?: UpdateDocument401ApplicationJSON;

    /**
     * Forbidden
     */
    @SpeakeasyMetadata()
    updateDocument403ApplicationJSONObject?: UpdateDocument403ApplicationJSON;

    /**
     * Not Found
     */
    @SpeakeasyMetadata()
    updateDocument404ApplicationJSONObject?: UpdateDocument404ApplicationJSON;
}
