/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class UpdateDepartmentRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    departmentWrite?: shared.DepartmentWrite;

    /**
     * Id of the company
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=company" })
    company: number;

    /**
     * Id of the department
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=department" })
    department: number;
}

export class UpdateDepartment422ApplicationJSONErrors extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "errors" })
    errors?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "field" })
    field?: string;
}

/**
 * Invalid data posted
 */
export class UpdateDepartment422ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: UpdateDepartment422ApplicationJSONErrors })
    @Expose({ name: "errors" })
    @Type(() => UpdateDepartment422ApplicationJSONErrors)
    errors?: UpdateDepartment422ApplicationJSONErrors[];

    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Not Found
 */
export class UpdateDepartment404ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Forbidden
 */
export class UpdateDepartment403ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * Unauthenticated
 */
export class UpdateDepartment401ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message?: string;
}

/**
 * OK
 */
export class UpdateDepartment200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.DepartmentRead)
    data?: shared.DepartmentRead;
}

export class UpdateDepartmentResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    updateDepartment200ApplicationJSONObject?: UpdateDepartment200ApplicationJSON;

    /**
     * Unauthenticated
     */
    @SpeakeasyMetadata()
    updateDepartment401ApplicationJSONObject?: UpdateDepartment401ApplicationJSON;

    /**
     * Forbidden
     */
    @SpeakeasyMetadata()
    updateDepartment403ApplicationJSONObject?: UpdateDepartment403ApplicationJSON;

    /**
     * Not Found
     */
    @SpeakeasyMetadata()
    updateDepartment404ApplicationJSONObject?: UpdateDepartment404ApplicationJSON;

    /**
     * Invalid data posted
     */
    @SpeakeasyMetadata()
    updateDepartment422ApplicationJSONObject?: UpdateDepartment422ApplicationJSON;
}
